# Generated by Django 3.0.3 on 2021-01-14 16:33

from django.db import migrations, models
import django.db.models.deletion
import schedule.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(validators=[schedule.validators.validate_schedule_day], verbose_name='Dia')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completa')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctor.Doctor', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['-day'],
                'unique_together': {('doctor', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='schedule.Schedule', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Hórarios',
                'ordering': ['-hour'],
                'unique_together': {('schedule', 'hour')},
            },
        ),
    ]
