# Generated by Django 3.0.3 on 2021-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Agenda completa'),
        ),
    ]
