# Generated by Django 3.0.3 on 2021-01-14 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especiality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('crm', models.CharField(max_length=10, unique=True, verbose_name='CRM')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='E-mail')),
                ('phone', models.CharField(max_length=14, null=True, verbose_name='Telefone')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True, verbose_name='Ativo')),
                ('especiality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialitiy', to='especiality.Especiality', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Médico(a)',
                'verbose_name_plural': 'Médicos(as)',
                'ordering': ['-created'],
            },
        ),
    ]
