# Generated by Django 3.0.3 on 2021-01-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('scheduling_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do agendamento')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultationdoctor', to='doctor.Doctor', verbose_name='Médico')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultationschedule', to='schedule.ScheduleHour')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-scheduling_date'],
            },
        ),
    ]
