# Generated by Django 3.0.3 on 2021-01-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0003_auto_20210115_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('M', 'MARCADA'), ('R', 'REALIZADA'), ('C', 'CANCELADA')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultations', to='doctor.Doctor', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='schedule.ScheduleHour'),
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('patient', 'schedule')},
        ),
    ]
