# Generated by Django 3.0.3 on 2021-01-16 20:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210116_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0005_auto_20210116_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dia da consulta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('patient', 'schedule')},
        ),
    ]
