# Generated by Django 3.0.3 on 2021-01-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20210116_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set(),
        ),
    ]
